---
- name: use motd role playbook
  hosts: all

  tasks:
    - name: run echo command
      command: /bin/echo hello world
      
    - name: Install apache packages 
      yum:
        name: httpd
        state: absent
        
    - name: ensure httpd is running
      service:
        name: httpd 
        state: stopped
