---
- name: use motd role playbook
  hosts: all

  tasks:    
    - name: Install apache packages 
      yum:
        name: httpd
        state: absent

    - name: Display hosts contents
      command: cat hosts chdir=/etc
      register: command_output

    - name: Print to console
      debug:
        msg: "{{command_output.stdout}}"
